platform :ios, '13.0'
use_frameworks!

target 'App' do
  pod 'Capacitor', '~> 6.0'
  pod 'CapacitorCordova', '~> 6.0'
  pod 'CapacitorApp', '~> 6.0'
  pod 'CapacitorCamera', '~> 6.0'
  pod 'CapacitorDevice', '~> 6.0'
  pod 'CapacitorGeolocation', '~> 6.0'
  pod 'CapacitorSplashScreen', '~> 6.0'
  pod 'CapacitorStatusBar', '~> 6.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
